# Generated by Django 4.2.3 on 2023-07-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='slug',
            new_name='recipe_slug',
        ),
    ]
