# Generated by Django 4.2.3 on 2023-07-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_rename_slug_category_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_slug',
            new_name='slug',
        ),
    ]
